### ISSUE TITLE
Password entry required?

### ISSUE THREAD

**Issue by pamelafox** [Arize-ai/phoenix-on-azure#10]
I was surprised to get prompted for two passwords. Could those parameters default to empty strings, so that there's no prompt?

You could change main.bicep like so:

```
@secure()
param databasePassword string = ''
```

<img width="1685" alt="Screenshot 2024-07-11 at 2 55 17 PM" src="https://github.com/user-attachments/assets/87309e7b-164f-415c-b9e7-b37843eb16bd">

**Comment by abalam666** [comment]
Thank you very much for your contribution @pamelafox
