### ISSUE TITLE
Readme link issue

### ISSUE THREAD

**Issue by jerryshia** [Arize-ai/phoenix-on-azure#14]
**Describe the issue:**
The link of the `Open in Github Codespace` and `DEV CONTAINERS` is error.
When clicking the button in the following image,
![image](https://github.com/user-attachments/assets/a52bc051-7b8f-47c6-a136-767a7495da72)

![image](https://github.com/user-attachments/assets/e117ddb1-7b99-4e1d-873b-eb459af82ac0)

it will redirect to the page shown in the following image:

![image](https://github.com/user-attachments/assets/5abd7fc4-afe5-4c43-900a-bcb5fea53eca)

**Suggestion:**
Add link`https://github.com/codespaces/new/arize-ai/phoenix-on-azure` to ` Open in Github Codespace`.
Add link`https://vscode.dev/redirect?url=vscode://ms-vscode-remote.remote-containers/cloneInVolume?url=https://github.com/arize-ai/phoenix-on-azure` to ` DEV CONTAINERS`.

@jongio and @loopingz and @abalam666  for notification.

**Comment by abalam666** [comment]
Thank you for contribution!
(but please do not tag everyone, thanks!)
