### ISSUE TITLE
Run the command `azd pipeline config` fail

### ISSUE THREAD

**Issue by jerryshia** [Arize-ai/phoenix-on-azure#16]
**Describe the issue:**
When run `azd pipeline config` , the result was successful in terminal, but there is no workflow on GitHub.
![image](https://github.com/user-attachments/assets/6fa15d1f-9b1d-4dd0-a10c-19e307b0d583)
![image](https://github.com/user-attachments/assets/b5a431ae-7edd-4cdb-aa35-bee0b45b8477)

**Repro Steps:**

1. Open the project
2. Run `azd auth login`
3. Run `azd pipeline config`

**Environment:**

- Azd version: azd version 1.9.5 (commit cd2b7af9995d358aab33c782614f801ac1997dde)
- OS: Codespace ,VS Code Dev Containers，Local

Expected behavior:
Run `azd pipeline config` successfully and there is some workflow running on GitHub. 

@jongio and @loopingz and @abalam666  for notification.

**Comment by abalam666** [comment]
Hello, 
Thank you for your contribution!
I am not sure to understand what you expect from the tool ?
The pipeline creation is not generated by our scripts in this repo, but by `azd`, isn't it ?

**Comment by jongio** [comment]
Yes, azd pipeline config allows the end user to easily setup a pipeline by creating the SP and setting GH secrets.  It's a good idea to include a deafult azure-dev.yml file in .github/workflows so the user has a sample pipeline.  We have some of those azure-dev.yml files here, which you can use as-is or modify to suit your needs. https://github.com/Azure/azure-dev/tree/main/templates/common/.github/workflows

**Comment by abalam666** [comment]
Ok, let's add a github default config azure-dev file
