### ISSUE TITLE
Data is not persisted

### ISSUE THREAD

**Issue by monuminu** [Arize-ai/phoenix-on-azure#6]
Hi Team,

I have deployed this but i see data is not persisted and i see my data is lost every time in login to the UI in 12 hours . How can i make this persistent ?

Thanks
Mano

**Comment by loopingz** [comment]
Hi,

Did you deploy with the `azd env set PERSISTENCE true`? By default we just deploy a version that will not persist, just to experience phoenix. If you set the persistence, then a postgres server is used to store the data and should be persisted.
